site_name: markupy
site_url: https://markupy.witiz.com
repo_url: https://github.com/witiz/markupy
theme:
  name: material
  palette:
    primary: blue
  features:
    - content.code.copy
    - toc.integrate
  icon:
    logo: material/code-tags
nav:
  - README.md
  - usage.md
  - components.md
  - html2markupy.md
  - flask.md
  - starlette.md
  - django.md
extra:
  analytics:
    provider: google
    property: G-NWHXG5WE1Q
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables